[tool.poetry]
name = "celery-yaml"
version = "0.1.3"
description = ""
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = ">=4"
pyramid = { version = ">=1.9", optional = true}
plaster-yaml = { version = "^0.1.1", optional = true}
PyYAML = "^5.4.1"

[tool.poetry.extras]
pyramid = ["pyramid", "plaster-yaml"]

[tool.poetry.dev-dependencies]
black = "^21.4b0"
isort = "^5.8.0"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
