[tool.poetry]
name = "celery-yaml"
version = "0.4.0"
description = "Easy configuration for celery app using Yaml file"
readme = "README.md"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
include = ["CHANGELOG.md"]
license = "BSD-derived"

[tool.poetry.dependencies]
python = "^3.7"
celery = ">=4"
pyramid = { version = ">=1.9", optional = true }
plaster-yaml = { version = "^0.1.3", optional = true }
PyYAML = "^6.0"

[tool.poetry.extras]
pyramid = ["pyramid", "plaster-yaml"]

[tool.poetry.group.dev.dependencies]
black = "^21.4b0"
isort = "^5.8.0"
mypy = "^0.991"
pytest = "^6"
pyramid-helloworld = { version = "^0.2.1", extras = ["celery"] }
types-pyyaml = "^6.0.12.3"
types-setuptools = "^65.7.0.4"
celery-stubs = "^0.1.2"


[[tool.mypy.overrides]]
module = "sequoia_api_recovery.*"
disallow_any_generics = true
disallow_untyped_defs = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
